# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_Kakao_Login_API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'KakaoSDKUser'

  # Pods for Test_Kakao_Login_API

end